name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/fazirmfahmy
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        only-labels: 'waiting-for-response'
        stale-issue-message: 'message'
        days-before-stale: 14
        days-before-close: 2
